# Use postgres/example user/password credentials
version: '3.1'

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
     - 8000:80
    volumes:
     - pgadmin-data:/var/lib/pgadmin 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: develop
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  pgadmin-data:
